version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"  # Map the container's port 5000 to EC2's port 5000 (not directly needed for nginx, but can be useful for debugging)
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80 of the EC2 instance
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map the Nginx config file
    depends_on:
      - web
    networks:
      - flask_network

networks:
  flask_network:
    name: rahman_flask_network #explicitly naming the network. Matches your previous network name.
    driver: bridge